### PR TITLE
Finalize metrics and pipeline

### PR DESCRIPTION
**Pull request by ndrwhoang**

### CODE REVIEW

**Review by BakerAugust — CHANGES_REQUESTED** [review]
@ndrwhoang it looks like there's a lot of good stuff here, but also some random stuff like `paper_gt_old.py` and `algorithm_on_roc_old.ipynb`. Do have a sense of what are the critical new contributions here?

**Comment by ndrwhoang** [comment]
My bad, I didn't clean up the old commits. The main changes should only be in `metric_testing.ipynb` and `metric_graphing.ipynb`.

**Review by ndrwhoang — COMMENTED** [review]
Remove redundant files

**Review by BakerAugust — APPROVED** [review]
Looks good. Thanks @ndrwhoang !

**Pull request merged**
